//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiathlonEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypStartu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypStartu()
        {
            this.Wyniki = new HashSet<Wyniki>();
        }
    
        public int NrTypu { get; set; }
        public string NazwaTypu { get; set; }
        public string Dystans { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyniki> Wyniki { get; set; }
    }
}
