//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiathlonEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wyniki
    {
        public int NrWyniku { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string MiejsceZawodow { get; set; }
        public int RodzajStartu { get; set; }
        public Nullable<int> MiejsceZajete { get; set; }
        public int Zawodnik { get; set; }
        public Nullable<int> IloscPudel { get; set; }
        public Nullable<System.TimeSpan> Czas { get; set; }
        public string RangaZawodow { get; set; }
    
        public virtual TypStartu TypStartu { get; set; }
        public virtual Zawodnik Zawodnik1 { get; set; }
    }
}
